baseURL = 'https://flpcastro.dev'
languageCode = 'en'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = 'Felipe Castro'
theme = 'PaperMod'
author = 'Felipe Castro'
enableRobotsTXT = true
summaryLength = 100
pygmentsUseClasses = true
pygmentsCodefences = true
hasCJKLanguage = false
enableEmoji = true

[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 1
    title = "Felipe Castro"
    [languages.en.params]
      description = "Writing about Go, JavaScript and technology."

  [languages.pt]
    languageCode = "pt-br"
    languageName = "Português"
    weight = 2
    title = "Felipe Castro"
    [languages.pt.params]
      description = "Escrevendo sobre Go, JavaScript e tecnologia."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Felipe"
  description = "Writing about Go, JavaScript and technology."
  mainSections = ["posts"]
  disableSocialShare = true
  disableIndexSummary = false
  disableAnchorHeading = false
  disableBreadcrumb = false
  disableComment = true
  mathRender = false
  enableFullContentRSS = true

[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "posts/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "about/"
  weight = 2

[[menu.footer]]
  identifier = "github"
  url = "https://github.com/flpcastro"
  name = "GitHub"

[[menu.footer]]
  identifier = "email"
  url = "mailto:flpc.dev@gmail.com"
  name = "Email"

[[menu.footer]]
  identifier = "linkedin"
  url = "https://linkedin.com/in/felipe-de-castro-curto"
  name = "LinkedIn"

[taxonomies]
  category = "categories"
  tag = "tags"
